# Generated by Django 3.2.4 on 2021-08-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='birds/photos/'),
        ),
    ]
