# Generated by Django 3.2.4 on 2021-08-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_alter_birdphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdphoto',
            name='photo',
            field=models.ImageField(default='https://mirmir.pythonanywhere.com/birds/photos/IMG_7623.jpg', upload_to='birds/photos/'),
            preserve_default=False,
        ),
    ]
